### ISSUE TITLE
use inputs rather than hard coded lists or sets

### ISSUE THREAD

**Issue by aaronlippold** [GoogleCloudPlatform/inspec-gcp-pci-profile#9]
on many of the controls I am seeing a hardcoded list of ports, etc. to make the profile have the ability to account for organizational adjustments - aka 'overlays' - move these sets to shared inputs in the inspec.yml so that organizations can tailor their profiles easily should they add or perhaps remove allowed ports, accounts, etc. more easily and not having to modify the controls.

**Comment by aaronlippold** [comment]
https://github.com/mitre/microsoft-windows-10-stig-baseline/blob/jb-windows10-controls-enhancements/inspec.yml

For example, the above allows us to easily update for environments etc.

**Comment by KonradSchieban** [comment]
> https://github.com/mitre/microsoft-windows-10-stig-baseline/blob/jb-windows10-controls-enhancements/inspec.yml
> 
> For example, the above allows us to easily update for environments etc.

This repo seems private / or non-existent. Can you please point to similar examples?

**Comment by aaronlippold** [comment]
That branch has been merged into master just hop to master and you'll see
the example

**Comment by binamov** [comment]
This was fixed in https://github.com/GoogleCloudPlatform/inspec-gcp-pci-profile/pull/18
